### ISSUE TITLE
FTP crashes when connecting

### ISSUE THREAD

**Issue by kachijs** [DarkModderVC/PS4JB#13]
Executing FTP payload it starts to listen on 1337 port.
When trying to connect:

> tatus:	Waiting to retry...
> Status:	Connecting to XXXXXXXXXX:1337...
> Status:	Connection established, waiting for welcome message...
> Status:	Plain FTP is insecure. Please switch to FTP over TLS.
> Status:	Server does not support non-ASCII characters.
> Status:	Logged in
> Status:	Retrieving directory listing...
> Command:	PWD
> Response:	257 "/" is the current directory.
> Command:	TYPE I
> Response:	200 Okay
> Command:	PASV
> Response:	227 Entering Passive Mode (XXX,XXX,X,XXX,XXX,XX)
> Command:	LIST
> Error:	Connection closed by server
> Error:	Failed to retrieve directory listing
> Status:	Disconnected from server
> Status:	Connecting to XXX.XXX.X.XXX:1337...
> Status:	Connection attempt failed with "ECONNREFUSED - Connection refused by server".
> Error:	Could not connect to server
> Status:	Waiting to retry...

On PS4 i get There is not enough free system memory.

**Comment by DarkModderVC** [comment]
Fixed Now please check
