### ISSUE TITLE
when activating the fan threshold fan activating very fast in all games

### ISSUE THREAD

**Issue by cronopsxploit** [DarkModderVC/PS4JB#14]
friend first congratulations for the great job.

I activated your jailbreak both offline and online, cleaning everything, with cash etc .....
the first time I went to test the fanthreshold, it sets the ps4 temperature to 60ºC and that is very little and because of that it activates the fan every time you enter any game.
at the time of 5.05, the cooler fan was set to 73ºC making the cooler stay on at a good speed, without making a fuss and preventing the ps4 from heating up.
would you like to change the temperature set, or create a new screen or modal so that the user sets the desired temperature?
I'm andexando as was the index of the 5.05 of the coole fan, used from ps-phowar

[files.zip](https://github.com/DarkModderVC/PS4JB/files/4975610/files.zip)

**Comment by DarkModderVC** [comment]
Fixed
