### ISSUE TITLE
Can not fund you via Paypal (from Germany)

### ISSUE THREAD

**Issue by gotwig** [DarkModderVC/PS4JB#15]
Just saying "this user cant accept personal donations" or something, just as a service.

Can you maybe setup Github Funding :) Cheers

**Comment by cypheron** [comment]
@gotwig Find the original project here: https://github.com/sleirsgoevy/ps4jb
The original author, who created this jailbreak, doesn't even have a donations link, but then this guy here makes a small change and sets up a donations link. Just saying, greedy imho.
