### ISSUE TITLE
Fan speed increase at 60 °C 

### ISSUE THREAD

**Issue by kamikam** [DarkModderVC/PS4JB#17]
Thanx for the great job.

the fanthreshold is sets  to 60ºC, please make it to 70ºC or adjustable, the actual configuration ( 60ºC) is very loud.

Thank you in advance.

**Comment by DarkModderVC** [comment]
You are facing this issue in running which payload ?

**Comment by peyman47** [comment]
> Hi kamikam,
> You are facing this issue in running which payload ?

please recompile fan thershod with 68c 70c

**Comment by kamikam** [comment]
Tha

> Hi kamikam,
> You are facing this issue in running which payload ?

Helo, its withe fan thershod payload.

**Comment by peyman47** [comment]
https://github.com/Scene-Collective/ps4-fan-threshold

**Comment by peyman47** [comment]
https://github.com/toxxic407/PS4-fan-control-payloads/tree/master/Multi%20FW

**Comment by DarkModderVC** [comment]
Fixed
