### ISSUE TITLE
External HDD issue

### ISSUE THREAD

**Issue by ShahdadLTF** [DarkModderVC/PS4JB#24]
Thank you so much for your outstanding job. There is an issue with the Mira+Hen. If you have a usb external hdd attached as an external storage for game installs, the games does not work from the external storage. This is quite an important issue to be resolved!

**Comment by mtnjustme** [comment]
> 
> 
> Thank you so much for your outstanding job. There is an issue with the Mira+Hen. If you have a usb external hdd attached as an external storage for game installs, the games does not work from the external storage. This is quite an important issue to be resolved!

use no hb

**Comment by DarkModderVC** [comment]
Use MIRA UnOfficial !!
